### ISSUE TITLE
Consider moving CAS to platform-standard cache directories

### ISSUE THREAD

**Issue by kamalmarhubi** [a-scie/jump#47]
Ran across this project via [pantsbuild.slack.com lurking](https://pantsbuild.slack.com/archives/C0D7TNJHL/p1667868071295209?thread_ts=1667868048.808669&cid=C0D7TNJHL).

Small suggestion: instead of `~/.nce`, store the CAS in `$XDG_CACHE_HOME/{scie,nce,whatever}` on systems that follow XDG, and in `~/Library/Caches/{scie,nce,whatever}` on macos—and probably somewhere under `%localappdata%` on Windows; less sure about that one.

This makes it clear it's fine to blow away (eg, to free up space), and also removes some clutter from `$HOME`. It's probably easier to change this before widespread use of scie-packaged programs. :-)

_Edit:_ I just saw #9 which probably conflicts with the idea that the CAS can be blown away. In that case, the equivalent of `$XDG_DATA_HOME` might be better?

**Comment by jsirois** [comment]
To be clear, `~/.nce` is just the default. It will be good to get that default conforming to XDG / Mac / Windows standards for user caches, but the author of a lift manifest can also explicitly set `scie.lift.base`. Since lift manifests are, by definition, platform specific, this works. Its more effort than needed though and defaulting correctly would be great.

**Comment by jsirois** [comment]
As to #9, the CAS definitely can always be blown away. The self-modifying idea is aimed at system installers; i.e.: `/var/nce` or `/var/lib/nce` or something like that would be used by the system and the installs would run as root. No one could easily blow away that sort of NCE cache.

**Comment by jsirois** [comment]
This is now released in 0.4.0: https://github.com/a-scie/jump/releases/tag/v0.4.0
